version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://zookeeper:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "senhadificil"
      MYSQL_DATABASE: "pokemons"
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
  spark-master:
    image: amauri/spark-master
    container_name: spark_master
    restart: always
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./spark-jobs:/home/python-jobs
      - ./jobs-data:/home/jobs-data
  spark-worker-1:
    image: amauri/spark-worker
    container_name: spark_worker-1
    restart: always
    depends_on:
      - spark-master
    links:
      - "spark-master:spark-master"
    environment:
      MASTER_PORT_7077_TCP_ADDR: "spark://spark-master"
      MASTER_PORT_7077_TCP_PORT: "7077"
    volumes:
      - ./spark-jobs:/home/python-jobs
      - ./jobs-data:/home/jobs-data
  spark-worker-2:
    image: amauri/spark-worker
    container_name: spark_worker-2
    restart: always
    depends_on:
      - spark-master
    links:
      - "spark-master:spark-master"
    environment:
      MASTER_PORT_7077_TCP_ADDR: "spark://spark-master"
      MASTER_PORT_7077_TCP_PORT: "7077"
    volumes:
      - ./spark-jobs:/home/python-jobs
      - ./jobs-data:/home/jobs-data
